services:
  chatbot:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-gemma3:latest}
    volumes:
      - ./app:/app/app
      - ./public:/app/public
      - ./next.config.js:/app/next.config.js
      - ./tsconfig.json:/app/tsconfig.json
      - ./postcss.config.js:/app/postcss.config.js
      - ./tailwind.config.ts:/app/tailwind.config.ts
      - next_build:/app/.next
    restart: unless-stopped
    depends_on:
      - ollama
    command: sh -c "npm run build && npm start"

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data:
  next_build:
