services:
  chatbot:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-gemma3:latest}
    volumes:
      - next_build:/app/.next
    restart: unless-stopped
    depends_on:
      - ollama
    command: sh -c "npm run build && npm start"

  # The model puller service
  model-init:
    image: curlimages/curl:latest
    depends_on:
      - ollama
    restart: "no"
    entrypoint: >
      sh -c "
        echo 'Waiting for Ollama to start...' &&
        sleep 15 &&
        echo 'Pulling model...' &&
        curl -X POST http://ollama:11434/api/pull -d '{\"name\": \"gemma3:latest\"}' &&
        echo 'Model pulled successfully!'
      "

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama
    restart: unless-stopped

volumes:
  ollama_data:
  next_build:
