services:
  chatbot:
    build: .
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - OLLAMA_HOST=http://ollama:11434
      - OLLAMA_MODEL=${OLLAMA_MODEL:-gemma3:latest}
    volumes:
      - .:/app
    restart: unless-stopped
    depends_on:
      ollama-init:
        condition: service_completed_successfully

  ollama:
    image: ollama/ollama:latest
    volumes:
      - ollama_data:/root/.ollama
    ports:
      - "11434:11434"
    restart: unless-stopped

  ollama-init:
    image: ollama/ollama:latest
    depends_on:
      - ollama
    command: >
      sh -c "
        echo 'Waiting for Ollama service to be ready...' &&
        for i in {1..30}; do
          if wget -q --spider http://ollama:11434/api/tags; then
            echo 'Ollama service is up!' &&
            echo 'Pulling Gemma3 1B model (smaller, ~815MB)...' &&
            ollama pull gemma3:latest &&
            echo 'Model pulled successfully!' &&
            exit 0;
          fi;
          echo 'Waiting...' &&
          sleep 2;
        done;
        echo 'Ollama service failed to start in time!' &&
        exit 1;
      "
    restart: on-failure

volumes:
  ollama_data: